ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Used Licenses

== .NET Core

Using .NET Core development environment and packages
Copyright (c) .NET Foundation and Contributors
[MIT License]
https://github.com/dotnet/core/blob/master/LICENSE.TXT

== Bootstrap

Using partially https://getbootstrap.com/ released under MIT license.

Code and documentation copyright 2011-2020 the 
[Bootstrap Authors] (https://github.com/twbs/bootstrap/graphs/contributors) and 
[Twitter, Inc.] (https://twitter.com) Code released under the 
[MIT License]
MIT: (https://github.com/twbs/bootstrap/blob/main/LICENSE). 
Docs released under [Creative Commons](https://creativecommons.org/licenses/by/3.0/).

XUnit
-----
MIT License: 
https://github.com/ploeh/ZeroToNine/blob/master/LICENCE


 C5
----
MIT License: https://github.com/sestoft/C5/blob/master/LICENSE.txt



Moq4
----
[BSD 3-Clause License]
Copyright (c) 2007, Clarius Consulting, Manas Technology Solutions, InSTEDD,
and Contributors. All rights reserved.

BSD License: https://github.com/moq/moq4/blob/master/License.txt


Xamarin / XUnit
---------------
Copyright 2014 Outercurve Foundation

Apache 2.0 License: https://github.com/xamarin/xunit/blob/master/license.txt



MatBlazor: https://github.com/SamProf/MatBlazor/blob/master/LICENSE
---------------

MIT License

Copyright (c) 2018 Vladimir Samoilenko 

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.